In [1]:
# Import libraries 
import numpy as np 
import pandas as pd 
# Import label encoder 
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import jaccard_similarity_score

from sklearn.model_selection import train_test_split

# Import dataset 
df = pd.read_csv('/home/devvrat/Documents/Flight_Delay_Prediction/Data/Processed_data15.csv')

In [2]:
df.head(90)

    year  month  day carrier origin dest  delayed
0   2013      1    1      UA    EWR  IAH        0
1   2013      1    1      UA    LGA  IAH        1
2   2013      1    1      AA    JFK  MIA        1
3   2013      1    1      B6    JFK  BQN        0
4   2013      1    1      DL    LGA  ATL        0
5   2013      1    1      UA    EWR  ORD        0
6   2013      1    1      B6    EWR  FLL        1
7   2013      1    1      EV    LGA  IAD        0
8   2013      1    1      B6    JFK  MCO        0
9   2013      1    1      AA    LGA  ORD        0
10  2013      1    1      B6    JFK  PBI        0
11  2013      1    1      B6    JFK  TPA        0
12  2013      1    1      UA    JFK  LAX        0
13  2013      1    1      UA    EWR  SFO        0
14  2013      1    1      AA    LGA  DFW        1
15  2013      1    1      B6    JFK  BOS        0
16  2013      1    1      UA    EWR  LAS        0
17  2013      1    1      B6    LGA  FLL        0
18  2013      1    1      MQ    LGA  ATL        0
19  2013      1    1      B6    EWR  PBI        0
20  2013      1    1      DL    LGA  MSP        0
21  2013      1    1      MQ    LGA  DTW        1
22  2013      1    1      AA    EWR  MIA        0
23  2013      1    1      DL    JFK  ATL        0
24  2013      1    1      UA    EWR  MIA        0
25  2013      1    1      MQ    EWR  ORD        1
26  2013      1    1      UA    JFK  SFO        0
27  2013      1    1      B6    JFK  RSW        0
28  2013      1    1      B6    JFK  SJU        0
29  2013      1    1      DL    EWR  ATL        0
..   ...    ...  ...     ...    ...  ...      ...
60  2013      1    1      UA    EWR  TPA        0
61  2013      1    1      DL    LGA  FLL        0
62  2013      1    1      DL    LGA  ATL        0
63  2013      1    1      VX    JFK  LAX        0
64  2013      1    1      AA    LGA  MIA        0
65  2013      1    1      B6    JFK  FLL        0
66  2013      1    1      DL    LGA  DTW        0
67  2013      1    1      UA    EWR  RSW        0
68  2013      1    1      UA    EWR  SJU        0
69  2013      1    1      B6    JFK  LAX        1
70  2013      1    1      UA    LGA  ORD        1
71  2013      1    1      B6    JFK  SJU        0
72  2013      1    1      AA    JFK  FLL        0
73  2013      1    1      UA    EWR  ORD        1
74  2013      1    1      FL    LGA  MKE        0
75  2013      1    1      B6    JFK  MCO        0
76  2013      1    1      UA    EWR  PBI        0
77  2013      1    1      AA    LGA  DFW        1
78  2013      1    1      AS    EWR  SEA        0
79  2013      1    1      AA    EWR  DFW        0
80  2013      1    1      UA    EWR  DEN        0
81  2013      1    1      UA    LGA  IAH        0
82  2013      1    1      VX    JFK  SFO        0
83  2013      1    1      B6    JFK  ROC        0
84  2013      1    1      B6    LGA  RSW        0
85  2013      1    1      UA    EWR  MCO        1
86  2013      1    1      B6    JFK  SYR        0
87  2013      1    1      B6    JFK  SFO        0
88  2013      1    1      AA    LGA  ORD        0
89  2013      1    1      UA    EWR  IAH        1

[90 rows x 7 columns]

In [3]:
columns= ['carrier','dest', 'origin']
le=LabelEncoder()
for i in columns:
     df[i]=le.fit_transform(df[i])

In [4]:
df['carrier'].unique()

array([11,  1,  3,  4,  5,  9, 12, 14, 13,  7,  2,  0,  6,  8, 15, 10])

In [5]:
df['origin'].unique()

array([0, 2, 1])

In [6]:
df['dest'].unique()

array([ 43,  57,  12,   4,  68,  35,  42,  53,  70,  99,  49,  89,  30,
        11,  48,  60,  32,  82,  91,  73,  16,  23,  14,  29,  94,  61,
        92, 103,  58,  88,  81,  98,  95,  79,  24,  47,  21,  55,  74,
        83,  28,  22,  96,  64,  46,  54,  40,  10,   5,  13,  72,  97,
        33,   6,  78,  45,  85,  19,  41,  51,  27,   2,   7,  56,  59,
        37,  26,  15,  80,  38,  36,  52,  69,  84,  87,  71,  90,  67,
        25,  65,  93, 102,  77,  31,  75, 100,   9,  66,  18,  39,  17,
        62,  34,  76,   1,   8,   0,  44,  63,  86,  50,  20, 101,   3])

In [7]:
df.head(90)

    year  month  day  carrier  origin  dest  delayed
0   2013      1    1       11       0    43        0
1   2013      1    1       11       2    43        1
2   2013      1    1        1       1    57        1
3   2013      1    1        3       1    12        0
4   2013      1    1        4       2     4        0
5   2013      1    1       11       0    68        0
6   2013      1    1        3       0    35        1
7   2013      1    1        5       2    42        0
8   2013      1    1        3       1    53        0
9   2013      1    1        1       2    68        0
10  2013      1    1        3       1    70        0
11  2013      1    1        3       1    99        0
12  2013      1    1       11       1    49        0
13  2013      1    1       11       0    89        0
14  2013      1    1        1       2    30        1
15  2013      1    1        3       1    11        0
16  2013      1    1       11       0    48        0
17  2013      1    1        3       2    35        0
18  2013      1    1        9       2     4        0
19  2013      1    1        3       0    70        0
20  2013      1    1        4       2    60        0
21  2013      1    1        9       2    32        1
22  2013      1    1        1       0    57        0
23  2013      1    1        4       1     4        0
24  2013      1    1       11       0    57        0
25  2013      1    1        9       0    68        1
26  2013      1    1       11       1    89        0
27  2013      1    1        3       1    82        0
28  2013      1    1        3       1    91        0
29  2013      1    1        4       0     4        0
..   ...    ...  ...      ...     ...   ...      ...
60  2013      1    1       11       0    99        0
61  2013      1    1        4       2    35        0
62  2013      1    1        4       2     4        0
63  2013      1    1       13       1    49        0
64  2013      1    1        1       2    57        0
65  2013      1    1        3       1    35        0
66  2013      1    1        4       2    32        0
67  2013      1    1       11       0    82        0
68  2013      1    1       11       0    91        0
69  2013      1    1        3       1    49        1
70  2013      1    1       11       2    68        1
71  2013      1    1        3       1    91        0
72  2013      1    1        1       1    35        0
73  2013      1    1       11       0    68        1
74  2013      1    1        7       2    58        0
75  2013      1    1        3       1    53        0
76  2013      1    1       11       0    70        0
77  2013      1    1        1       2    30        1
78  2013      1    1        2       0    88        0
79  2013      1    1        1       0    30        0
80  2013      1    1       11       0    29        0
81  2013      1    1       11       2    43        0
82  2013      1    1       13       1    89        0
83  2013      1    1        3       1    81        0
84  2013      1    1        3       2    82        0
85  2013      1    1       11       0    53        1
86  2013      1    1        3       1    98        0
87  2013      1    1        3       1    89        0
88  2013      1    1        1       2    68        0
89  2013      1    1       11       0    43        1

[90 rows x 7 columns]

In [8]:
X = df.iloc[:, 0:6].values # from column(years) to column(distance)
X[0:5]

array([[2013,    1,    1,   11,    0,   43],
       [2013,    1,    1,   11,    2,   43],
       [2013,    1,    1,    1,    1,   57],
       [2013,    1,    1,    3,    1,   12],
       [2013,    1,    1,    4,    2,    4]])

In [9]:
y = df['delayed']
y.head().to_frame()

   delayed
0        0
1        1
2        1
3        0
4        0

In [10]:
'''for i in range(0, 3):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=i)
    
    #creating random forest classifier
    clf = RandomForestClassifier(random_state=i)
    clf.fit(X_train, y_train)
    
    #determining the score
    train_score = clf.score(X_train, y_train)
    test_score = clf.score(X_test, y_test)
    print("Test: {}, Train: {} and Random State: {}".format(test_score, train_score, i))
    '''

'for i in range(0, 3):\n    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=i)\n    \n    #creating random forest classifier\n    clf = RandomForestClassifier(random_state=i)\n    clf.fit(X_train, y_train)\n    \n    #determining the score\n    train_score = clf.score(X_train, y_train)\n    test_score = clf.score(X_test, y_test)\n    print("Test: {}, Train: {} and Random State: {}".format(test_score, train_score, i))\n    '

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=18)
clf = RandomForestClassifier(random_state=18)
clf.fit(X_train, y_train)

/home/devvrat/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=18, verbose=0,
                       warm_start=False)

In [12]:
print("Train set: ", clf.score(X_train, y_train))

Train set:  0.8299410612238248

In [13]:
print("Test set: ", clf.score(X_test, y_test))

Test set:  0.6994146901768149

In [14]:
# predicting the trained Classifier to the test
yhat = clf.predict(X_test)

In [15]:
# Viewing the predicted probabilities of first 10 observations
yhat_prob = clf.predict_proba(X_test)[:10]

In [16]:
print(classification_report(y_test, yhat))

              precision    recall  f1-score   support

           0       0.77      0.83      0.80     58830
           1       0.46      0.36      0.40     23007

    accuracy                           0.70     81837
   macro avg       0.61      0.59      0.60     81837
weighted avg       0.68      0.70      0.69     81837

In [17]:
df1 = pd.DataFrame([2013, 1, 1 ,11, 0, 53])
m = df1.iloc[:, :6].values
a = clf.predict(m)
a

ValueError: Number of features of the model must match the input. Model n_features is 6 and input n_features is 1